name: Build

on:
  workflow_call:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "12.x"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.19.3"
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Check lint
        run: flutter analyze

      - name: Create the Keystore for signature
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
        run: echo $KEY_JKS | base64 -d > android/key.jks

      - name: Start release build apk
        env:
          ALIAS: ${{ secrets.ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
        run: |
          flutter build apk --no-pub --release --build-number=${{github.run_number}} --build-name=${{github.ref_name}}
          flutter build apk --release --split-per-abi --target-platform android-arm,android-arm64,android-x64 --build-number=${{github.run_number}} --build-name=${{github.ref_name}}

      - name: "Upload apk to Artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/app/outputs/flutter-apk/*.apk
          retention-days: 5

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ github.token }}
          WITH_V: true
