name: Pre release

on:
  workflow_dispatch:
  push:
    tags: "v*"

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    secrets: inherit

  prerelease:
    name: Publish to PlayStore
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: apk

      - name: Publish to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.a2a.appel
          releaseFiles: "*.apk"
          status: draft
