name: Release tag

on:
  push:
    tags:
      - "**"

jobs:
  build:
    if: ${{startsWith(github.ref, 'refs/tags/') }}
    uses: ./.github/workflows/build.yaml
    secrets: inherit

  release:
    if: ${{startsWith(github.ref, 'refs/tags/') }}
    name: Release in GitHub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download apk previously build
        uses: actions/download-artifact@v4
        with:
          name: apk
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            *.apk

  publish:
    if: ${{startsWith(github.ref, 'refs/tags/') }}
    name: Publish to PlayStore
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: apk

      - name: Publish to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.a2a.appel
          releaseFiles: "*.apk"
          track: production
          status: draft
